# Generated by Django 3.0 on 2023-11-02 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="profile",
                    table="profiles_profile",
                ),
            ],
            database_operations=[],
        ),
    ]
