
services:
  - type: web
    name: oc-lettings-site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn oc-lettings-site.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oc-lettings-site
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4