version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python3.11.1

    working_directory: ~/repo

    steps:
      - checkout

      # Image Docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t al3xbrs/oc_lettings_site:latest .

      # Push Docker on Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push al3xbrs/oc_lettings_site:latest

    deploy:
      render:
        if: github.ref == 'refs/heads/master'
        - env:
          hook_url: ${{ os.environ.get("HOOK_URL") }}
        - run:
            name: Deploy on Render
            command: |
              curl "$hook_url"



  workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build:
            filters:
              branches:
                only: master
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
