# Generated by Django 3.0 on 2023-11-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='letting',
                    table=None,
                ),
            ],
            database_operations=[],
        ),
    ]
