# Generated by Django 3.0 on 2023-11-02 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("letting", "0002_auto_20231102_0058"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="letting",
                    table="letting_letting",
                ),
            ],
            database_operations=[],
        ),
    ]
