# Generated by Django 3.0 on 2023-11-02 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="profile",
                    name="user",
                ),
                migrations.AlterModelTable(
                    name="address",
                    table="oc_lettings_site_address",
                ),
                migrations.DeleteModel(
                    name="Letting",
                ),
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[],
        ),
    ]
