# Generated by Django 3.0 on 2023-11-02 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0002_auto_20231102_0210"),
        ("oc_lettings_site", "0002_auto_20231102_0158"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Address",
                ),
            ],
            database_operations=[],
        )
    ]
